version: '3.8'

services:
  sorare-mlb-scoreboard:
    build: .
    container_name: sorare-mlb-scoreboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
